# Generated by Django 3.1.7 on 2021-03-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviespy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=50)),
                ('pelicula', models.CharField(max_length=100)),
                ('url_pelicula', models.CharField(max_length=100)),
                ('tipo_funcion', models.CharField(max_length=30)),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.CharField(max_length=6)),
                ('sala', models.CharField(max_length=10)),
                ('asientos', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
