# Generated by Django 3.1.7 on 2021-03-13 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviespy', '0003_auto_20210313_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
