# Generated by Django 3.1.7 on 2021-03-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviespy', '0004_auto_20210313_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
