# Generated by Django 3.1.7 on 2021-03-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviespy', '0005_auto_20210313_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='funcion',
            name='num_func',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funcion',
            name='num_hors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='asientos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviespy.cine')),
            ],
        ),
        migrations.AlterField(
            model_name='funcion',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviespy.dias'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviespy.sucursales'),
        ),
    ]
