# Generated by Django 3.1.7 on 2021-03-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviespy', '0006_auto_20210318_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dias',
            new_name='Dia',
        ),
        migrations.RenameModel(
            old_name='Sucursales',
            new_name='Sucursal',
        ),
    ]
